# Router 3 — 链状拓扑 R1—R2—R3，R3 只连 R2

id        = "3";
udp_port  = 5203;
tcp_port  = 8023;

neighbors = (
    { id = "2";  address = "127.0.0.1";  port = 5202; }
);

networks = (
    { address = "10.0.3.0/24"; }
);
